name: MATSgp-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  ## top level dependencies
  - python=3.8
  - setuptools
  - numpy
  - pandas
  - matplotlib
  # mats stuff
  - lmfit
  - sympy
  - seaborn
  - scipy
  - qgrid
  ## developmental stuff
  # linting
  - black
  - blackdoc
  - flake8
  - isort
  # testing
  - pytest
  - pytest-cov
  - tox-conda
  # hooks
  - pre-commit
 # repl
  - ipython
  - ipykernel
  # build
  - setuptools
  - setuptools-scm
  - twine
  # conda specific
  - conda-build
  - anaconda-client
  - greyskull
  # doc stuff
  - sphinx
  - sphinx_rtd_theme
  - recommonmark # if want markdown
  - nbsphinx # if want notebooks
  # lsp stuff
  - autoflake
  - pyls-mypy
  - pyls-black
  - pyls-isort
  # pip stuff last
  - pip
  - pip:
      - git+https://github.com/wpk-nist-gov/MATS.git@cci-from-Development
      - tensorflow
      - tensorflow-probability
      - gpflow
