name: MATSgp-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python=3.8
  - setuptools
  - MATS-dependencies
  # - setuptools
  # - numpy
  # - pandas
  # # optional?
  # - matplotlib
  # # mats stuff
  # - lmfit
  # - mpmath
  # - seaborn
  # - scipy
  # - qgrid
  - pip
  - pip:
      - https://raw.githubusercontent.com/wpk-nist-gov/MATS/feature/master-reformat/wheel/MATS-3-py3-none-any.whl
      - tensorflow
      - tensorflow-probability
      - gpflow
