name: MATSgp-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python=3.8
  - setuptools
  - numpy
  - pandas
  # optional?
  - matplotlib
  # mats stuff
  - lmfit
  - sympy
  - seaborn
  - scipy
  - qgrid
  - pip
  - pip:
      - git+https://github.com/wpk-nist-gov/MATS.git@cci-from-Development
      - tensorflow
      - tensorflow-probability
      - gpflow
