name: MATSgp-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  ## top level dependencies
  - python=3.8
  - setuptools
  - MATS-dependencies
   ## developmental stuff
  # linting
  - black
  - blackdoc
  - flake8
  - isort
  # testing
  - pytest
  - pytest-cov
  - tox-conda
  # hooks
  - pre-commit
 # repl
  - ipython
  - ipykernel
  # build
  - setuptools
  - setuptools-scm
  - twine
  # conda specific
  - conda-build
  - anaconda-client
  - greyskull
  # doc stuff
  - sphinx
  - sphinx_rtd_theme
  - recommonmark # if want markdown
  - nbsphinx # if want notebooks
  # lsp stuff
  - autoflake
  - pyls-mypy
  - pyls-black
  - pyls-isort
  # pip stuff last
  - pip
  - pip:
      - https://raw.githubusercontent.com/wpk-nist-gov/MATS/feature/master-reformat/wheel/MATS-3-py3-none-any.whl
      - tensorflow
      - tensorflow-probability
      - gpflow
